//
//  Generated by scripts/import-bezels.swift from Bezels. Do not edit.
//

import CoreGraphics

enum BezelCatalog {

    static let all: [Bezel] = [
        Bezel(
            model: "iPhone 18 Pro Max",
            color: "Black",
            pose: .portrait,
            imageName: "iPhone 18 Pro Max - Black - Portrait",
            canvasSize: CGSize(width: 1470, height: 3000),
            screenRect: CGRect(x: 75, y: 66, width: 1320, height: 2868)
        ),
        Bezel(
            model: "iPhone 18 Pro Max",
            color: "Black",
            pose: .landscape,
            imageName: "iPhone 18 Pro Max - Black - Landscape",
            canvasSize: CGSize(width: 3000, height: 1470),
            screenRect: CGRect(x: 66, y: 76, width: 2868, height: 1320)
        ),
        Bezel(
            model: "iPhone 18 Pro Max",
            color: "Burgundy",
            pose: .portrait,
            imageName: "iPhone 18 Pro Max - Burgundy - Portrait",
            canvasSize: CGSize(width: 1470, height: 3000),
            screenRect: CGRect(x: 75, y: 66, width: 1320, height: 2868)
        ),
        Bezel(
            model: "iPhone 18 Pro Max",
            color: "Burgundy",
            pose: .landscape,
            imageName: "iPhone 18 Pro Max - Burgundy - Landscape",
            canvasSize: CGSize(width: 3000, height: 1470),
            screenRect: CGRect(x: 66, y: 76, width: 2868, height: 1320)
        ),
        Bezel(
            model: "iPhone 18 Pro Max",
            color: "Glacier",
            pose: .portrait,
            imageName: "iPhone 18 Pro Max - Glacier - Portrait",
            canvasSize: CGSize(width: 1470, height: 3000),
            screenRect: CGRect(x: 75, y: 66, width: 1320, height: 2868)
        ),
        Bezel(
            model: "iPhone 18 Pro Max",
            color: "Glacier",
            pose: .landscape,
            imageName: "iPhone 18 Pro Max - Glacier - Landscape",
            canvasSize: CGSize(width: 3000, height: 1470),
            screenRect: CGRect(x: 66, y: 76, width: 2868, height: 1320)
        ),
        Bezel(
            model: "iPhone 18 Pro Max",
            color: "Silver",
            pose: .portrait,
            imageName: "iPhone 18 Pro Max - Silver - Portrait",
            canvasSize: CGSize(width: 1470, height: 3000),
            screenRect: CGRect(x: 75, y: 66, width: 1320, height: 2868)
        ),
        Bezel(
            model: "iPhone 18 Pro Max",
            color: "Silver",
            pose: .landscape,
            imageName: "iPhone 18 Pro Max - Silver - Landscape",
            canvasSize: CGSize(width: 3000, height: 1470),
            screenRect: CGRect(x: 66, y: 76, width: 2868, height: 1320)
        ),
        Bezel(
            model: "iPhone 18 Pro",
            color: "Black",
            pose: .portrait,
            imageName: "iPhone 18 Pro - Black - Portrait",
            canvasSize: CGSize(width: 1350, height: 2760),
            screenRect: CGRect(x: 72, y: 69, width: 1206, height: 2622)
        ),
        Bezel(
            model: "iPhone 18 Pro",
            color: "Black",
            pose: .landscape,
            imageName: "iPhone 18 Pro - Black - Landscape",
            canvasSize: CGSize(width: 2760, height: 1350),
            screenRect: CGRect(x: 69, y: 72, width: 2622, height: 1206)
        ),
        Bezel(
            model: "iPhone 18 Pro",
            color: "Burgundy",
            pose: .portrait,
            imageName: "iPhone 18 Pro - Burgundy - Portrait",
            canvasSize: CGSize(width: 1350, height: 2760),
            screenRect: CGRect(x: 72, y: 69, width: 1206, height: 2622)
        ),
        Bezel(
            model: "iPhone 18 Pro",
            color: "Burgundy",
            pose: .landscape,
            imageName: "iPhone 18 Pro - Burgundy - Landscape",
            canvasSize: CGSize(width: 2760, height: 1350),
            screenRect: CGRect(x: 69, y: 72, width: 2622, height: 1206)
        ),
        Bezel(
            model: "iPhone 18 Pro",
            color: "Glacier",
            pose: .portrait,
            imageName: "iPhone 18 Pro - Glacier - Portrait",
            canvasSize: CGSize(width: 1350, height: 2760),
            screenRect: CGRect(x: 72, y: 69, width: 1206, height: 2622)
        ),
        Bezel(
            model: "iPhone 18 Pro",
            color: "Glacier",
            pose: .landscape,
            imageName: "iPhone 18 Pro - Glacier - Landscape",
            canvasSize: CGSize(width: 2760, height: 1350),
            screenRect: CGRect(x: 69, y: 72, width: 2622, height: 1206)
        ),
        Bezel(
            model: "iPhone 18 Pro",
            color: "Silver",
            pose: .portrait,
            imageName: "iPhone 18 Pro - Silver - Portrait",
            canvasSize: CGSize(width: 1350, height: 2760),
            screenRect: CGRect(x: 72, y: 69, width: 1206, height: 2622)
        ),
        Bezel(
            model: "iPhone 18 Pro",
            color: "Silver",
            pose: .landscape,
            imageName: "iPhone 18 Pro - Silver - Landscape",
            canvasSize: CGSize(width: 2760, height: 1350),
            screenRect: CGRect(x: 69, y: 72, width: 2622, height: 1206)
        ),
        Bezel(
            model: "iPhone Duo",
            color: "Night Sky",
            pose: .outerClosedPortrait,
            imageName: "iPhone Duo - Night Sky - Outer Closed Portrait",
            canvasSize: CGSize(width: 1574, height: 2194),
            screenRect: CGRect(x: 88, y: 80, width: 1398, height: 2034)
        ),
        Bezel(
            model: "iPhone Duo",
            color: "Night Sky",
            pose: .outerClosedLandscape,
            imageName: "iPhone Duo - Night Sky - Outer Closed Landscape",
            canvasSize: CGSize(width: 2194, height: 1574),
            screenRect: CGRect(x: 80, y: 88, width: 2034, height: 1398)
        ),
        Bezel(
            model: "iPhone Duo",
            color: "Night Sky",
            pose: .outerOpen,
            imageName: "iPhone Duo - Night Sky - Outer Open",
            canvasSize: CGSize(width: 3056, height: 2194),
            screenRect: CGRect(x: 1570, y: 80, width: 1398, height: 2034)
        ),
        Bezel(
            model: "iPhone Duo",
            color: "Night Sky",
            pose: .innerOpenPortrait,
            imageName: "iPhone Duo - Night Sky - Inner Open Portrait",
            canvasSize: CGSize(width: 2247, height: 3093),
            screenRect: CGRect(x: 120, y: 120, width: 2007, height: 2853)
        ),
        Bezel(
            model: "iPhone Duo",
            color: "Night Sky",
            pose: .innerOpenLandscape,
            imageName: "iPhone Duo - Night Sky - Inner Open Landscape",
            canvasSize: CGSize(width: 3093, height: 2247),
            screenRect: CGRect(x: 120, y: 120, width: 2853, height: 2007)
        ),
        Bezel(
            model: "iPhone Duo",
            color: "Star White",
            pose: .outerClosedPortrait,
            imageName: "iPhone Duo - Star White - Outer Closed Portrait",
            canvasSize: CGSize(width: 1574, height: 2194),
            screenRect: CGRect(x: 88, y: 80, width: 1398, height: 2034)
        ),
        Bezel(
            model: "iPhone Duo",
            color: "Star White",
            pose: .outerClosedLandscape,
            imageName: "iPhone Duo - Star White - Outer Closed Landscape",
            canvasSize: CGSize(width: 2194, height: 1574),
            screenRect: CGRect(x: 80, y: 88, width: 2034, height: 1398)
        ),
        Bezel(
            model: "iPhone Duo",
            color: "Star White",
            pose: .outerOpen,
            imageName: "iPhone Duo - Star White - Outer Open",
            canvasSize: CGSize(width: 3056, height: 2194),
            screenRect: CGRect(x: 1570, y: 80, width: 1398, height: 2034)
        ),
        Bezel(
            model: "iPhone Duo",
            color: "Star White",
            pose: .innerOpenPortrait,
            imageName: "iPhone Duo - Star White - Inner Open Portrait",
            canvasSize: CGSize(width: 2247, height: 3093),
            screenRect: CGRect(x: 120, y: 120, width: 2007, height: 2853)
        ),
        Bezel(
            model: "iPhone Duo",
            color: "Star White",
            pose: .innerOpenLandscape,
            imageName: "iPhone Duo - Star White - Inner Open Landscape",
            canvasSize: CGSize(width: 3093, height: 2247),
            screenRect: CGRect(x: 120, y: 120, width: 2853, height: 2007)
        ),
        Bezel(
            model: "iPhone 17 Pro Max",
            color: "Cosmic Orange",
            pose: .portrait,
            imageName: "iPhone 17 Pro Max - Cosmic Orange - Portrait",
            canvasSize: CGSize(width: 1470, height: 3000),
            screenRect: CGRect(x: 75, y: 66, width: 1320, height: 2868)
        ),
        Bezel(
            model: "iPhone 17 Pro Max",
            color: "Cosmic Orange",
            pose: .landscape,
            imageName: "iPhone 17 Pro Max - Cosmic Orange - Landscape",
            canvasSize: CGSize(width: 3000, height: 1470),
            screenRect: CGRect(x: 66, y: 75, width: 2868, height: 1320)
        ),
        Bezel(
            model: "iPhone 17 Pro Max",
            color: "Deep Blue",
            pose: .portrait,
            imageName: "iPhone 17 Pro Max - Deep Blue - Portrait",
            canvasSize: CGSize(width: 1470, height: 3000),
            screenRect: CGRect(x: 75, y: 66, width: 1320, height: 2868)
        ),
        Bezel(
            model: "iPhone 17 Pro Max",
            color: "Deep Blue",
            pose: .landscape,
            imageName: "iPhone 17 Pro Max - Deep Blue - Landscape",
            canvasSize: CGSize(width: 3000, height: 1470),
            screenRect: CGRect(x: 66, y: 75, width: 2868, height: 1320)
        ),
        Bezel(
            model: "iPhone 17 Pro Max",
            color: "Silver",
            pose: .portrait,
            imageName: "iPhone 17 Pro Max - Silver - Portrait",
            canvasSize: CGSize(width: 1470, height: 3000),
            screenRect: CGRect(x: 75, y: 66, width: 1320, height: 2868)
        ),
        Bezel(
            model: "iPhone 17 Pro Max",
            color: "Silver",
            pose: .landscape,
            imageName: "iPhone 17 Pro Max - Silver - Landscape",
            canvasSize: CGSize(width: 3000, height: 1470),
            screenRect: CGRect(x: 66, y: 75, width: 2868, height: 1320)
        ),
        Bezel(
            model: "iPhone 17 Pro",
            color: "Cosmic Orange",
            pose: .portrait,
            imageName: "iPhone 17 Pro - Cosmic Orange - Portrait",
            canvasSize: CGSize(width: 1350, height: 2760),
            screenRect: CGRect(x: 72, y: 69, width: 1206, height: 2622)
        ),
        Bezel(
            model: "iPhone 17 Pro",
            color: "Cosmic Orange",
            pose: .landscape,
            imageName: "iPhone 17 Pro - Cosmic Orange - Landscape",
            canvasSize: CGSize(width: 2760, height: 1350),
            screenRect: CGRect(x: 69, y: 72, width: 2622, height: 1206)
        ),
        Bezel(
            model: "iPhone 17 Pro",
            color: "Deep Blue",
            pose: .portrait,
            imageName: "iPhone 17 Pro - Deep Blue - Portrait",
            canvasSize: CGSize(width: 1350, height: 2760),
            screenRect: CGRect(x: 72, y: 69, width: 1206, height: 2622)
        ),
        Bezel(
            model: "iPhone 17 Pro",
            color: "Deep Blue",
            pose: .landscape,
            imageName: "iPhone 17 Pro - Deep Blue - Landscape",
            canvasSize: CGSize(width: 2760, height: 1350),
            screenRect: CGRect(x: 69, y: 72, width: 2622, height: 1206)
        ),
        Bezel(
            model: "iPhone 17 Pro",
            color: "Silver",
            pose: .portrait,
            imageName: "iPhone 17 Pro - Silver - Portrait",
            canvasSize: CGSize(width: 1350, height: 2760),
            screenRect: CGRect(x: 72, y: 69, width: 1206, height: 2622)
        ),
        Bezel(
            model: "iPhone 17 Pro",
            color: "Silver",
            pose: .landscape,
            imageName: "iPhone 17 Pro - Silver - Landscape",
            canvasSize: CGSize(width: 2760, height: 1350),
            screenRect: CGRect(x: 69, y: 72, width: 2622, height: 1206)
        ),
        Bezel(
            model: "iPhone Air",
            color: "Cloud White",
            pose: .portrait,
            imageName: "iPhone Air - Cloud White - Portrait",
            canvasSize: CGSize(width: 1380, height: 2880),
            screenRect: CGRect(x: 60, y: 72, width: 1260, height: 2736)
        ),
        Bezel(
            model: "iPhone Air",
            color: "Cloud White",
            pose: .landscape,
            imageName: "iPhone Air - Cloud White - Landscape",
            canvasSize: CGSize(width: 2880, height: 1380),
            screenRect: CGRect(x: 72, y: 60, width: 2736, height: 1260)
        ),
        Bezel(
            model: "iPhone Air",
            color: "Light Gold",
            pose: .portrait,
            imageName: "iPhone Air - Light Gold - Portrait",
            canvasSize: CGSize(width: 1380, height: 2880),
            screenRect: CGRect(x: 60, y: 72, width: 1260, height: 2736)
        ),
        Bezel(
            model: "iPhone Air",
            color: "Light Gold",
            pose: .landscape,
            imageName: "iPhone Air - Light Gold - Landscape",
            canvasSize: CGSize(width: 2880, height: 1380),
            screenRect: CGRect(x: 72, y: 60, width: 2736, height: 1260)
        ),
        Bezel(
            model: "iPhone Air",
            color: "Sky Blue",
            pose: .portrait,
            imageName: "iPhone Air - Sky Blue - Portrait",
            canvasSize: CGSize(width: 1380, height: 2880),
            screenRect: CGRect(x: 60, y: 72, width: 1260, height: 2736)
        ),
        Bezel(
            model: "iPhone Air",
            color: "Sky Blue",
            pose: .landscape,
            imageName: "iPhone Air - Sky Blue - Landscape",
            canvasSize: CGSize(width: 2880, height: 1380),
            screenRect: CGRect(x: 72, y: 60, width: 2736, height: 1260)
        ),
        Bezel(
            model: "iPhone Air",
            color: "Space Black",
            pose: .portrait,
            imageName: "iPhone Air - Space Black - Portrait",
            canvasSize: CGSize(width: 1380, height: 2880),
            screenRect: CGRect(x: 60, y: 72, width: 1260, height: 2736)
        ),
        Bezel(
            model: "iPhone Air",
            color: "Space Black",
            pose: .landscape,
            imageName: "iPhone Air - Space Black - Landscape",
            canvasSize: CGSize(width: 2880, height: 1380),
            screenRect: CGRect(x: 72, y: 60, width: 2736, height: 1260)
        ),
        Bezel(
            model: "iPhone 17",
            color: "Black",
            pose: .portrait,
            imageName: "iPhone 17 - Black - Portrait",
            canvasSize: CGSize(width: 1350, height: 2760),
            screenRect: CGRect(x: 72, y: 69, width: 1206, height: 2622)
        ),
        Bezel(
            model: "iPhone 17",
            color: "Black",
            pose: .landscape,
            imageName: "iPhone 17 - Black - Landscape",
            canvasSize: CGSize(width: 2760, height: 1350),
            screenRect: CGRect(x: 69, y: 72, width: 2622, height: 1206)
        ),
        Bezel(
            model: "iPhone 17",
            color: "Lavender",
            pose: .portrait,
            imageName: "iPhone 17 - Lavender - Portrait",
            canvasSize: CGSize(width: 1350, height: 2760),
            screenRect: CGRect(x: 72, y: 69, width: 1206, height: 2622)
        ),
        Bezel(
            model: "iPhone 17",
            color: "Lavender",
            pose: .landscape,
            imageName: "iPhone 17 - Lavender - Landscape",
            canvasSize: CGSize(width: 2760, height: 1350),
            screenRect: CGRect(x: 69, y: 72, width: 2622, height: 1206)
        ),
        Bezel(
            model: "iPhone 17",
            color: "Mist Blue",
            pose: .portrait,
            imageName: "iPhone 17 - Mist Blue - Portrait",
            canvasSize: CGSize(width: 1350, height: 2760),
            screenRect: CGRect(x: 72, y: 69, width: 1206, height: 2622)
        ),
        Bezel(
            model: "iPhone 17",
            color: "Mist Blue",
            pose: .landscape,
            imageName: "iPhone 17 - Mist Blue - Landscape",
            canvasSize: CGSize(width: 2760, height: 1350),
            screenRect: CGRect(x: 69, y: 72, width: 2622, height: 1206)
        ),
        Bezel(
            model: "iPhone 17",
            color: "Sage",
            pose: .portrait,
            imageName: "iPhone 17 - Sage - Portrait",
            canvasSize: CGSize(width: 1350, height: 2760),
            screenRect: CGRect(x: 72, y: 69, width: 1206, height: 2622)
        ),
        Bezel(
            model: "iPhone 17",
            color: "Sage",
            pose: .landscape,
            imageName: "iPhone 17 - Sage - Landscape",
            canvasSize: CGSize(width: 2760, height: 1350),
            screenRect: CGRect(x: 69, y: 72, width: 2622, height: 1206)
        ),
        Bezel(
            model: "iPhone 17",
            color: "White",
            pose: .portrait,
            imageName: "iPhone 17 - White - Portrait",
            canvasSize: CGSize(width: 1350, height: 2760),
            screenRect: CGRect(x: 72, y: 69, width: 1206, height: 2622)
        ),
        Bezel(
            model: "iPhone 17",
            color: "White",
            pose: .landscape,
            imageName: "iPhone 17 - White - Landscape",
            canvasSize: CGSize(width: 2760, height: 1350),
            screenRect: CGRect(x: 69, y: 72, width: 2622, height: 1206)
        ),
        Bezel(
            model: "iPhone 16 Pro Max",
            color: "Black Titanium",
            pose: .portrait,
            imageName: "iPhone 16 Pro Max - Black Titanium - Portrait",
            canvasSize: CGSize(width: 1470, height: 3000),
            screenRect: CGRect(x: 75, y: 66, width: 1320, height: 2868)
        ),
        Bezel(
            model: "iPhone 16 Pro Max",
            color: "Black Titanium",
            pose: .landscape,
            imageName: "iPhone 16 Pro Max - Black Titanium - Landscape",
            canvasSize: CGSize(width: 3000, height: 1470),
            screenRect: CGRect(x: 66, y: 75, width: 2868, height: 1320)
        ),
        Bezel(
            model: "iPhone 16 Pro Max",
            color: "Desert Titanium",
            pose: .portrait,
            imageName: "iPhone 16 Pro Max - Desert Titanium - Portrait",
            canvasSize: CGSize(width: 1470, height: 3000),
            screenRect: CGRect(x: 75, y: 66, width: 1320, height: 2868)
        ),
        Bezel(
            model: "iPhone 16 Pro Max",
            color: "Desert Titanium",
            pose: .landscape,
            imageName: "iPhone 16 Pro Max - Desert Titanium - Landscape",
            canvasSize: CGSize(width: 3000, height: 1470),
            screenRect: CGRect(x: 66, y: 75, width: 2868, height: 1320)
        ),
        Bezel(
            model: "iPhone 16 Pro Max",
            color: "Natural Titanium",
            pose: .portrait,
            imageName: "iPhone 16 Pro Max - Natural Titanium - Portrait",
            canvasSize: CGSize(width: 1470, height: 3000),
            screenRect: CGRect(x: 75, y: 66, width: 1320, height: 2868)
        ),
        Bezel(
            model: "iPhone 16 Pro Max",
            color: "Natural Titanium",
            pose: .landscape,
            imageName: "iPhone 16 Pro Max - Natural Titanium - Landscape",
            canvasSize: CGSize(width: 3000, height: 1470),
            screenRect: CGRect(x: 66, y: 75, width: 2868, height: 1320)
        ),
        Bezel(
            model: "iPhone 16 Pro Max",
            color: "White Titanium",
            pose: .portrait,
            imageName: "iPhone 16 Pro Max - White Titanium - Portrait",
            canvasSize: CGSize(width: 1470, height: 3000),
            screenRect: CGRect(x: 75, y: 66, width: 1320, height: 2868)
        ),
        Bezel(
            model: "iPhone 16 Pro Max",
            color: "White Titanium",
            pose: .landscape,
            imageName: "iPhone 16 Pro Max - White Titanium - Landscape",
            canvasSize: CGSize(width: 3000, height: 1470),
            screenRect: CGRect(x: 66, y: 75, width: 2868, height: 1320)
        ),
        Bezel(
            model: "iPhone 16 Pro",
            color: "Black Titanium",
            pose: .portrait,
            imageName: "iPhone 16 Pro - Black Titanium - Portrait",
            canvasSize: CGSize(width: 1350, height: 2760),
            screenRect: CGRect(x: 72, y: 69, width: 1206, height: 2622)
        ),
        Bezel(
            model: "iPhone 16 Pro",
            color: "Black Titanium",
            pose: .landscape,
            imageName: "iPhone 16 Pro - Black Titanium - Landscape",
            canvasSize: CGSize(width: 2760, height: 1350),
            screenRect: CGRect(x: 69, y: 72, width: 2622, height: 1206)
        ),
        Bezel(
            model: "iPhone 16 Pro",
            color: "Desert Titanium",
            pose: .portrait,
            imageName: "iPhone 16 Pro - Desert Titanium - Portrait",
            canvasSize: CGSize(width: 1350, height: 2760),
            screenRect: CGRect(x: 72, y: 69, width: 1206, height: 2622)
        ),
        Bezel(
            model: "iPhone 16 Pro",
            color: "Desert Titanium",
            pose: .landscape,
            imageName: "iPhone 16 Pro - Desert Titanium - Landscape",
            canvasSize: CGSize(width: 2760, height: 1350),
            screenRect: CGRect(x: 69, y: 72, width: 2622, height: 1206)
        ),
        Bezel(
            model: "iPhone 16 Pro",
            color: "Natural Titanium",
            pose: .portrait,
            imageName: "iPhone 16 Pro - Natural Titanium - Portrait",
            canvasSize: CGSize(width: 1350, height: 2760),
            screenRect: CGRect(x: 72, y: 69, width: 1206, height: 2622)
        ),
        Bezel(
            model: "iPhone 16 Pro",
            color: "Natural Titanium",
            pose: .landscape,
            imageName: "iPhone 16 Pro - Natural Titanium - Landscape",
            canvasSize: CGSize(width: 2760, height: 1350),
            screenRect: CGRect(x: 69, y: 72, width: 2622, height: 1206)
        ),
        Bezel(
            model: "iPhone 16 Pro",
            color: "White Titanium",
            pose: .portrait,
            imageName: "iPhone 16 Pro - White Titanium - Portrait",
            canvasSize: CGSize(width: 1350, height: 2760),
            screenRect: CGRect(x: 72, y: 69, width: 1206, height: 2622)
        ),
        Bezel(
            model: "iPhone 16 Pro",
            color: "White Titanium",
            pose: .landscape,
            imageName: "iPhone 16 Pro - White Titanium - Landscape",
            canvasSize: CGSize(width: 2760, height: 1350),
            screenRect: CGRect(x: 69, y: 72, width: 2622, height: 1206)
        ),
        Bezel(
            model: "iPhone 16 Plus",
            color: "Black",
            pose: .portrait,
            imageName: "iPhone 16 Plus - Black - Portrait",
            canvasSize: CGSize(width: 1470, height: 2970),
            screenRect: CGRect(x: 90, y: 87, width: 1290, height: 2796)
        ),
        Bezel(
            model: "iPhone 16 Plus",
            color: "Black",
            pose: .landscape,
            imageName: "iPhone 16 Plus - Black - Landscape",
            canvasSize: CGSize(width: 2970, height: 1470),
            screenRect: CGRect(x: 87, y: 90, width: 2796, height: 1290)
        ),
        Bezel(
            model: "iPhone 16 Plus",
            color: "Pink",
            pose: .portrait,
            imageName: "iPhone 16 Plus - Pink - Portrait",
            canvasSize: CGSize(width: 1470, height: 2970),
            screenRect: CGRect(x: 90, y: 87, width: 1290, height: 2796)
        ),
        Bezel(
            model: "iPhone 16 Plus",
            color: "Pink",
            pose: .landscape,
            imageName: "iPhone 16 Plus - Pink - Landscape",
            canvasSize: CGSize(width: 2970, height: 1470),
            screenRect: CGRect(x: 87, y: 90, width: 2796, height: 1290)
        ),
        Bezel(
            model: "iPhone 16 Plus",
            color: "Teal",
            pose: .portrait,
            imageName: "iPhone 16 Plus - Teal - Portrait",
            canvasSize: CGSize(width: 1470, height: 2970),
            screenRect: CGRect(x: 90, y: 87, width: 1290, height: 2796)
        ),
        Bezel(
            model: "iPhone 16 Plus",
            color: "Teal",
            pose: .landscape,
            imageName: "iPhone 16 Plus - Teal - Landscape",
            canvasSize: CGSize(width: 2970, height: 1470),
            screenRect: CGRect(x: 87, y: 90, width: 2796, height: 1290)
        ),
        Bezel(
            model: "iPhone 16 Plus",
            color: "Ultramarine",
            pose: .portrait,
            imageName: "iPhone 16 Plus - Ultramarine - Portrait",
            canvasSize: CGSize(width: 1470, height: 2970),
            screenRect: CGRect(x: 90, y: 87, width: 1290, height: 2796)
        ),
        Bezel(
            model: "iPhone 16 Plus",
            color: "Ultramarine",
            pose: .landscape,
            imageName: "iPhone 16 Plus - Ultramarine - Landscape",
            canvasSize: CGSize(width: 2970, height: 1470),
            screenRect: CGRect(x: 87, y: 90, width: 2796, height: 1290)
        ),
        Bezel(
            model: "iPhone 16 Plus",
            color: "White",
            pose: .portrait,
            imageName: "iPhone 16 Plus - White - Portrait",
            canvasSize: CGSize(width: 1470, height: 2970),
            screenRect: CGRect(x: 90, y: 87, width: 1290, height: 2796)
        ),
        Bezel(
            model: "iPhone 16 Plus",
            color: "White",
            pose: .landscape,
            imageName: "iPhone 16 Plus - White - Landscape",
            canvasSize: CGSize(width: 2970, height: 1470),
            screenRect: CGRect(x: 87, y: 90, width: 2796, height: 1290)
        ),
        Bezel(
            model: "iPhone 16",
            color: "Black",
            pose: .portrait,
            imageName: "iPhone 16 - Black - Portrait",
            canvasSize: CGSize(width: 1359, height: 2736),
            screenRect: CGRect(x: 90, y: 90, width: 1179, height: 2556)
        ),
        Bezel(
            model: "iPhone 16",
            color: "Black",
            pose: .landscape,
            imageName: "iPhone 16 - Black - Landscape",
            canvasSize: CGSize(width: 2736, height: 1359),
            screenRect: CGRect(x: 90, y: 90, width: 2556, height: 1179)
        ),
        Bezel(
            model: "iPhone 16",
            color: "Pink",
            pose: .portrait,
            imageName: "iPhone 16 - Pink - Portrait",
            canvasSize: CGSize(width: 1359, height: 2736),
            screenRect: CGRect(x: 90, y: 90, width: 1179, height: 2556)
        ),
        Bezel(
            model: "iPhone 16",
            color: "Pink",
            pose: .landscape,
            imageName: "iPhone 16 - Pink - Landscape",
            canvasSize: CGSize(width: 2736, height: 1359),
            screenRect: CGRect(x: 90, y: 90, width: 2556, height: 1179)
        ),
        Bezel(
            model: "iPhone 16",
            color: "Teal",
            pose: .portrait,
            imageName: "iPhone 16 - Teal - Portrait",
            canvasSize: CGSize(width: 1359, height: 2736),
            screenRect: CGRect(x: 90, y: 90, width: 1179, height: 2556)
        ),
        Bezel(
            model: "iPhone 16",
            color: "Teal",
            pose: .landscape,
            imageName: "iPhone 16 - Teal - Landscape",
            canvasSize: CGSize(width: 2736, height: 1359),
            screenRect: CGRect(x: 90, y: 90, width: 2556, height: 1179)
        ),
        Bezel(
            model: "iPhone 16",
            color: "Ultramarine",
            pose: .portrait,
            imageName: "iPhone 16 - Ultramarine - Portrait",
            canvasSize: CGSize(width: 1359, height: 2736),
            screenRect: CGRect(x: 90, y: 90, width: 1179, height: 2556)
        ),
        Bezel(
            model: "iPhone 16",
            color: "Ultramarine",
            pose: .landscape,
            imageName: "iPhone 16 - Ultramarine - Landscape",
            canvasSize: CGSize(width: 2736, height: 1359),
            screenRect: CGRect(x: 90, y: 90, width: 2556, height: 1179)
        ),
        Bezel(
            model: "iPhone 16",
            color: "White",
            pose: .portrait,
            imageName: "iPhone 16 - White - Portrait",
            canvasSize: CGSize(width: 1359, height: 2736),
            screenRect: CGRect(x: 90, y: 90, width: 1179, height: 2556)
        ),
        Bezel(
            model: "iPhone 16",
            color: "White",
            pose: .landscape,
            imageName: "iPhone 16 - White - Landscape",
            canvasSize: CGSize(width: 2736, height: 1359),
            screenRect: CGRect(x: 90, y: 90, width: 2556, height: 1179)
        )
    ]
}
